locales:
  skf:
    name: Sakirabiá Keyboards
    description: >-
      Mobile OS keyboards for the Sakirabiá language from the Divvun group
      at UiT.
  en:
    name: Sakirabiá Keyboards
    description: >-
      Mobile OS keyboards for the Sakirabiá language from the Divvun group
      at UiT.
  nb:
    name: Sakirabiá tastatur
    description: Mobiltastatur for Sakirabiá fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
