locales:
  skf:
    name: Sakurabiat Keyboards
    description: >-
      Mobile OS keyboards for the Sakurabiat language from the Divvun group
      at UiT.
  en:
    name: Sakurabiat Keyboards
    description: >-
      Mobile OS keyboards for the Sakurabiat language from the Divvun group
      at UiT.
  nb:
    name: Sakurabiat tastatur
    description: Mobiltastatur for Sakurabiat fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
